name: Build and release workflow

on:
  push:
    tags:
     - 'v*'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    name: Build and release
    runs-on: ubuntu-latest
    needs: test

    strategy:
      matrix:
        python-versions: [ "3.10", "3.11", "3.12" ]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-versions }}

    - name: Install poetry
      run: >-
        python -m pip install --upgrade pip
        pip install poetry

    - name: Build package
      run: >-
        poetry build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip_existing: true